### ISSUE TITLE
Add private key argument

### ISSUE THREAD

**Issue by tohsnoom** [phoreproject/vps#1]
Add the ability to specify the Phore Masternode private key as an argument to install.sh, which then will automatically replace that line in the Phore configuration file.

Note: A simple argument will not work if the script is used to install multiple masternodes that all need different private keys. We may need to add a validation check and error message if the script is used with both the multiple masternode and private key arguments.

Alternatively, we could add a prompt during script execution to ask the user to enter the private key for each masternode as the .conf file is created for that masternode. Upgrade mode may need to override this since it wouldn't need a new private key.

**Comment by liray-unendlich** [comment]
I added private key argument feature.
But it seems complicate.
Updated script supports privatekey validation check, error message.
And update wallet daemon.
